name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build tools
      run: sudo apt-get install build-essential

    - name: Build C and C++ programs
      run: |
        echo "Building using GCC" | gcc *.c -o c_program
        echo "Building using G++" | g++ *.cc -o cpp_program

    - name: Run C program
      run: |
        echo "Running C program:"
        echo "5" | ./c_program

    - name: Run C++ program
      run: |
        echo "Running C++ program:"
        echo "5" | ./cpp_program

    - name: Clean up
      run: make clean
